In [35]:
import pkt
import numpy as np
import math

from scipy.signal import welch

![r1](r1.jpg)

In [36]:
random_data = np.random.rand(120,250*8,8)

In [37]:
random_one_trail = random_data[np.random.randint(120)]

In [38]:
random_one_trail.shape

(2000, 8)

In [39]:
random_one_channel = random_one_trail[:,0]

In [40]:
random_one_channel.shape

(2000,)

## 信号统计量

### 平均值 µs

In [41]:
np.average(random_one_trail,axis=0)

array([0.51176763, 0.50259894, 0.50156883, 0.50457467, 0.4971679 ,
       0.49324753, 0.4898429 , 0.50156932])

In [42]:
np.average(random_one_channel,axis=0)

0.5117676286688916

In [91]:
def get_avg(data):
    return np.average(data,axis=0)

### 标准差

In [43]:
np.std(random_one_trail,axis=0)

array([0.29181719, 0.28955467, 0.28337244, 0.28839623, 0.28956764,
       0.28980272, 0.28448178, 0.2852392 ])

In [44]:
np.std(random_one_channel,axis=0)

0.29181719208924284

In [92]:
def get_std(data):
    return np.std(data,axis=0)

### 一阶差分绝对值的平均值

In [45]:
N = len(random_one_trail)

In [51]:
tmp = 0
for i in np.arange(N-1):
    tmp += np.abs(random_one_trail[i+1]-random_one_trail[i])
res = tmp/N

In [47]:
res

array([0.33698485, 0.32690359, 0.33058027, 0.32917191, 0.34049286,
       0.33604494, 0.33460628, 0.32939444])

In [48]:
N = len(random_one_channel)

In [52]:
tmp = 0
for i in np.arange(N-1):
    tmp += np.abs(random_one_channel[i+1]-random_one_channel[i])
res = tmp/N

In [53]:
res

0.33683391912918464

In [63]:
def first_order_difference(data):
    N = len(data)
    tmp = 0
    for i in np.arange(N-1):
        tmp += np.abs(data[i+1]-data[i])
    res = tmp/N
    return res

### 二阶差分绝对值的平均值

In [54]:
N = len(random_one_trail)

In [55]:
tmp = 0
for i in np.arange(N-2):
    tmp += np.abs(random_one_trail[i+2]-random_one_trail[i])
res = tmp/(N-1)

In [56]:
res

array([0.33593448, 0.33622835, 0.32787902, 0.33796906, 0.33939487,
       0.33102843, 0.33268641, 0.33039125])

In [57]:
N = len(random_one_channel)

In [58]:
tmp = 0
for i in np.arange(N-2):
    tmp += np.abs(random_one_channel[i+2]-random_one_channel[i])
res = tmp/(N-1)

In [59]:
res

0.3359344767753872

In [62]:
def second_order_difference(data):
    N = len(data)
    tmp = 0
    for i in np.arange(N-2):
        tmp += np.abs(data[i+2]-data[i])
    res = tmp/(N-1)
    return res

### 归一化的一阶差分

In [77]:
first_order_difference(random_one_trail)/np.std(random_one_trail,axis=0)

array([1.15426345, 1.12892598, 1.16674751, 1.14227751, 1.17572982,
       1.15992521, 1.17585665, 1.1550595 ])

In [78]:
first_order_difference(random_one_channel)/np.std(random_one_channel)

1.1542634507502727

### 归一化的二阶差分

In [81]:
second_order_difference(random_one_trail)/np.std(random_one_trail,axis=0)

array([1.15118124, 1.16119125, 1.15706036, 1.17189141, 1.17207457,
       1.14225439, 1.16944719, 1.15829538])

In [83]:
second_order_difference(random_one_channel)/np.std(random_one_channel)

1.1511812390842706

## 能量

In [97]:
N = len(random_one_trail)

In [98]:
tmp = 0
for i in np.arange(N):
    tmp += (random_one_trail[i])*(random_one_trail[i])

In [99]:
tmp

array([694.1267587 , 672.8952067 , 663.74246029, 675.53596813,
       662.05068448, 654.5574885 , 641.75188705, 665.86635953])

In [87]:
N = len(random_one_channel)

In [88]:
tmp = 0
for i in np.arange(N):
    tmp += (random_one_channel[i])*(random_one_channel[i])

In [89]:
tmp

694.1267587044597

In [102]:
def get_engery(data):
    N = len(data)
    tmp = 0
    for i in np.arange(N):
        tmp += (data[i])*(data[i])
    return tmp

## 功率

In [103]:
get_engery(random_one_trail)/len(random_one_trail)

array([0.34706338, 0.3364476 , 0.33187123, 0.33776798, 0.33102534,
       0.32727874, 0.32087594, 0.33293318])

In [104]:
get_engery(random_one_channel)/len(random_one_channel)

0.34706337935222986

## Hjorth 参数特征

### Activity

In [105]:
N = len(random_one_trail)

In [106]:
tmp = 0
avg_s = get_avg(random_one_trail)
for i in np.arange(N):
    tmp += ((random_one_trail[i])-avg_s)*((random_one_trail[i])-avg_s)
res = tmp/N

In [107]:
res

array([0.08515727, 0.08384191, 0.08029994, 0.08317238, 0.08384942,
       0.08398561, 0.08092988, 0.0813614 ])

In [108]:
N = len(random_one_channel)

In [109]:
tmp = 0
avg_s = get_avg(random_one_channel)
for i in np.arange(N):
    tmp += ((random_one_channel[i])-avg_s)*((random_one_channel[i])-avg_s)
res = tmp/N

In [110]:
res

0.08515727359885009

In [111]:
def get_hjorth_activity(data):
    N = len(data)
    tmp = 0
    avg_s = get_avg(data)
    for i in np.arange(N):
        tmp += ((data[i])-avg_s)*((data[i])-avg_s)
    res = tmp/N
    return res

### Mobility & Complexity

### reference: https://github.com/forrestbao/pyeeg/blob/master/pyeeg/hjorth_mobility_complexity.py

In [119]:
D = np.diff(random_one_trail,axis=0)

In [127]:
D = np.insert(D,0,0,axis=0)

In [128]:
D.shape

(2000, 8)

In [129]:
N = len(random_one_trail)

In [134]:
np.sum(D ** 2, axis=0)/N

array([0.17027464, 0.16266131, 0.16032849, 0.16275271, 0.17226434,
       0.16977231, 0.16565483, 0.16306328])

In [138]:
M2 = np.sum(D ** 2, axis = 0) / N
TP = np.sum(random_one_trail ** 2, axis = 0)
M4 = 0
for i in range(N-1):
    M4 += (D[i+1] - D[i]) ** 2
M4 = M4 / N

In [144]:
mobility = np.sqrt(M2 / TP)

In [145]:
mobility

array([0.0156623 , 0.01554778, 0.01554195, 0.01552172, 0.01613066,
       0.01610496, 0.0160664 , 0.01564893])

In [146]:
complexity = np.sqrt(M4 * TP / M2 / M2)

In [147]:
complexity

array([110.8059677 , 110.70239979, 111.29499241, 110.60606792,
       107.42443959, 108.05592492, 107.99569284, 110.5716442 ])

## 高阶过零分析(HOC)

### reference: https://github.com/ADI10HERO/pyHOC/blob/master/applied_maths/pyhoc.py

In [150]:
nzc = []
for i in range(10):
    curr_diff = np.diff(random_one_channel, n=i)

    x_t = curr_diff >= 0   # binary time series signal
    x_t = numpy.diff(x_t)  # taking diff of x_t
    x_t = numpy.abs(x_t)   # taking abs value

    count = np.count_nonzero(x_t)
    nzc.append(count)

In [151]:
nzc

[0, 1340, 1452, 1529, 1578, 1615, 1632, 1661, 1678, 1702]

## 整理

### 导包

In [4]:
import numpy as np
import math

from scipy.signal import welch

### 随机生成数据模拟脑电信号

In [6]:
random_data = np.random.rand(120,250*8,8)  ## 120个trail，每个trail 250*8个采样点， 8通道 
random_one_trail = random_data[np.random.randint(120)]  ## 从120个trail中随机获取1个

In [7]:
random_one_trail.shape  ## 1个trail数据形状

(2000, 8)

In [8]:
random_one_channel = random_one_trail[:,0]  ## 获取1个trail的第一个通道，0可修改为对应通道下标获取对应通道

In [9]:
random_one_channel.shape  ## 1个通道数据形状

(2000,)

### 平均值 µs

In [10]:
## data：可以是一个trail数据，也可以是单个通道数据
## return: trail/channel的平均值
def get_avg(data):
    return np.average(data,axis=0)

### 标准差

In [11]:
## data：可以是一个trail数据，也可以是单个通道数据
## return: trail/channel的平均值
def get_std(data):
    return np.std(data,axis=0)

### 一阶差分绝对值的平均值

In [12]:
## data：可以是一个trail数据，也可以是单个通道数据
## return: trail/channel一阶差分绝对值的平均值
def first_order_difference(data):
    N = len(data)
    tmp = 0
    for i in np.arange(N-1):
        tmp += np.abs(data[i+1]-data[i])
    res = tmp/N
    return res

In [15]:
first_order_difference(random_one_trail)

array([0.32576676, 0.32390288, 0.34379096, 0.33488424, 0.34047781,
       0.33780907, 0.32897112, 0.33134233])

In [16]:
first_order_difference(random_one_channel)

0.3257667567897728

### 二阶差分绝对值的平均值

In [17]:
## data：可以是一个trail数据，也可以是单个通道数据
## return: trail/channel二阶差分绝对值的平均值
def second_order_difference(data):
    N = len(data)
    tmp = 0
    for i in np.arange(N-2):
        tmp += np.abs(data[i+2]-data[i])
    res = tmp/(N-1)
    return res

In [18]:
second_order_difference(random_one_trail)

array([0.32574512, 0.3302874 , 0.33769602, 0.33676851, 0.33576959,
       0.33021852, 0.32914042, 0.32303282])

In [19]:
second_order_difference(random_one_channel)

0.32574511611436685

### 归一化的一阶差分

In [29]:
## data：可以是一个trail数据，也可以是单个通道数据
## return: trail/channel归一化的一阶差分
## 使用该函数时保证前面有求一阶差分绝对值的平均值函数即first_order_difference函数存在
def norm_first_order_difference(data):
    return first_order_difference(data)/np.std(data,axis=0)

In [30]:
norm_first_order_difference(random_one_trail)

array([1.15876184, 1.13072331, 1.16898225, 1.15850677, 1.15355936,
       1.16461315, 1.15303493, 1.14955205])

In [31]:
norm_first_order_difference(random_one_channel)

1.1587618388281546

### 归一化的二阶差分

In [32]:
## data：可以是一个trail数据，也可以是单个通道数据
## return: trail/channel归一化的二阶差分
## 使用该函数时保证前面有求二阶差分绝对值的平均值函数即second_order_difference函数存在
def norm_second_order_difference(data):
    return second_order_difference(data)/np.std(data,axis=0)

In [33]:
norm_second_order_difference(random_one_trail)

array([1.15868486, 1.15301122, 1.1482578 , 1.16502525, 1.13760765,
       1.13844436, 1.15362832, 1.12072319])

In [34]:
norm_second_order_difference(random_one_channel)

1.1586848623156525

### 能量

In [35]:
## data：可以是一个trail数据，也可以是单个通道数据
## return: trail/channel的能量
def get_engery(data):
    N = len(data)
    tmp = 0
    for i in np.arange(N):
        tmp += (data[i])*(data[i])
    return tmp

In [36]:
get_engery(random_one_trail)

array([666.21726168, 656.68807501, 679.48412969, 664.89253438,
       682.27868825, 675.41064515, 687.29730652, 656.53944777])

In [37]:
get_engery(random_one_channel)

666.217261683484

### 功率

In [39]:
## data：可以是一个trail数据，也可以是单个通道数据
## return: trail/channel的功率
def get_power(data):
    return get_engery(data)/len(data)

In [40]:
get_power(random_one_trail)

array([0.33310863, 0.32834404, 0.33974206, 0.33244627, 0.34113934,
       0.33770532, 0.34364865, 0.32826972])

In [41]:
get_power(random_one_channel)

0.333108630841742

### Hjorth 参数特征-activity

In [42]:
## data：可以是一个trail数据，也可以是单个通道数据
## return: trail/channel的Hjorth参数特征-activity
def get_hjorth_activity(data):
    N = len(data)
    tmp = 0
    avg_s = get_avg(data)
    for i in np.arange(N):
        tmp += ((data[i])-avg_s)*((data[i])-avg_s)
    res = tmp/N
    return res

In [43]:
get_hjorth_activity(random_one_trail)

array([0.07903604, 0.08205725, 0.08649143, 0.08355882, 0.08711596,
       0.08413549, 0.08140116, 0.08308002])

In [44]:
get_hjorth_activity(random_one_channel)

0.07903603772505868

### Hjorth 参数特征-mobility&complexity

#### reference: https://github.com/forrestbao/pyeeg/blob/master/pyeeg/hjorth_mobility_complexity.py

In [47]:
## data：单个trail数据
## return: trail的Hjorth参数特征-mobility&complexity
def get_hjorth_mobility_complexity(data):
    D = np.diff(data,axis=0)
    D = np.insert(D,0,0,axis=0)
    
    N = len(data)
    
    M2 = np.sum(D ** 2, axis = 0) / N
    TP = np.sum(data ** 2, axis = 0)
    M4 = 0
    for i in range(N-1):
        M4 += (D[i+1] - D[i]) ** 2
    M4 = M4 / N
    
    mobility = np.sqrt(M2 / TP)
    complexity = np.sqrt(M4 * TP / M2 / M2)
    
    return mobility, complexity

In [48]:
mobility, complexity = get_hjorth_mobility_complexity(random_one_trail)

In [49]:
mobility

array([0.01539158, 0.01558062, 0.01614394, 0.01589435, 0.0159241 ,
       0.01586119, 0.01546806, 0.01581843])

In [50]:
complexity

array([112.28903987, 110.78963876, 107.73866467, 108.98774655,
       108.93052918, 109.74974476, 112.24990972, 110.22592927])

### 高阶过零分析(HOC)


#### reference: https://github.com/ADI10HERO/pyHOC/blob/master/applied_maths/pyhoc.py

In [53]:
## data：单个trail数据
## return: trail的高阶过零分析(HOC)统计量
def get_hoc(data):
    nzc = []
    for i in range(10):
        curr_diff = np.diff(data, n=i)

        x_t = curr_diff >= 0   # binary time series signal
        x_t = np.diff(x_t)  # taking diff of x_t
        x_t = np.abs(x_t)   # taking abs value

        count = np.count_nonzero(x_t)
        nzc.append(count)
    return nzc

In [54]:
get_hoc(random_one_trail)

[0, 8008, 7232, 6166, 4773, 3242, 1660, 0, 0, 0]